version: '3'
services:
  desktop: # choose 2560x1440 for display
    image: hossein20s/nx-desktop
    container_name: desktop
    privileged: true
    ports:
      - 6080:80
      - 5900:5900
      - 6901:6901
      - 5000:5000
      - 4000:4000
      - 8000:8000
      - 63342:63342 # pycharm built-in server
    environment:
      USER: guest
      PASSWORD: guest
    cap_add:
      - SYS_PTRACE
    volumes:
      - /dev/shm:/dev/shm
      - apps:/opt/apps
      - dev:/opt/dev
      - R-package:/opt/R
      - packages:/opt/packages
      - ~:/opt/host
      - python:/opt/python
      - temp:/tmp
   methyl:
    image: joshualevy44/pymethylprocess
    container_name: methyl
    privileged: true
    command: tail -f /dev/null
    volumes:
      - dev:/opt/dev
      - R-package:/opt/R
      - src:/opt/lib
      - packages:/opt/packages
      - pycharm-conf:/opt/pycharm-conf
      - ~:/opt/host
      - python:/opt/python
volumes:
  R-package:
    external: true
  apps:
    external: true
  dev:
    external: true
  packages:
    external: true
  mysql:
    external: true
  python:
    external: true
  temp:
    external: true

